mysite/blog/urls.py
from django.conf.urls import url
from . import views
from .feeds import LatestPostsFeed

urlpatterns=[
    url(r'^$', views.post_list, name='post_list'),
    #url(r'^$', views.PostListView.as_view(), name='post_list'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)', views.post_detail, name='post_detail'),
    url(r'^(?P<post_id>\d+)/share/$', views.post_share, name='post_share'),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.post_list, name='post_list_by_tag'),
    url(r'^feed/$', LatestPostsFeed(), name='post_feed'),
]

mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSiteMap


sitemaps = {
    'posts': PostSiteMap,
}

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/',include('blog.urls', namespace='blog', app_name='blog')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps':sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

mysite/blog/models.py
from django.db import models
from taggit.managers import TaggableManager
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
#Create your models Manager


class PublishManager(models.Manager):
    def get_queryset(self):
        return super(PublishManager, self).get_queryset().filter(status='published')

# Create your models here.


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    objects = models.Manager()
    published = PublishManager()
    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[
            self.publish.year,
            self.publish.strftime('%m'),
            self.publish.strftime('%d'),
            self.slug,
        ])

class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return "Comment by {0} on {1}".format(self.name, self.post)

mysite/blog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

mysite/blog/views.py
from django.shortcuts import render,get_object_or_404
from django.db.models import Count
from .models import Post
from django.views.generic import ListView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import EmailPostForm,CommentForm
from django.core.mail import  send_mail
from taggit.models import Tag
# Create your views here.


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'



def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None
    tags = []
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    tags = Tag.objects.all()
    paginator = Paginator(object_list,3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html',{'posts':posts, 'page':page, 'tag':tag, 'tags':tags})

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year, publish__month=month, publish__day=day)
    comments = post.comments.filter(active=True)
    new_comment = None
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]

    if request.method == "POST":
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()
    return render(request, 'blog/post/detail.html', {'post': post,
                                                     'comments':comments,
                                                     'new_comment': new_comment,
                                                     'comment_form':comment_form,
                                                     'similar_posts':similar_posts})

def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    cd = None
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{0} ({1}) recommends you reading "{2}" '.format(cd['name'],cd['email'], post.title)
            message = 'Read "{0}" at {1} \n\n {2}\'s comments:{3}'.format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, '17673239962@163.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request,'blog/post/share.html',{
        'post':post,
        'form':form,
        'cd': cd,
        'sent': sent,
    })

mysite/blog/templates/blog/base.html
{% load blog_tags %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title%}{% endblock title%}</title>
    <link rel="stylesheet" href="{% static 'css/blog.css'%}">
</head>
<body>
    <div id="content">
        {% block content%}
        {% endblock content%}
    </div>
    <div id="sidebar">
        <h2>My blog</h2>
        <p>This is my blog. i've written {% total_posts %} post so far</p>
        <h3>
            Latest posts
        </h3>
        {% show_latest_posts 3 %}
        <h3>
            Most commented posts
        </h3>
        {% get_most_commented_posts as most_commented_posts %}
        <ul>
            {% for post in  most_commented_posts %}
            <li>
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </li>
            {% endfor %}
        </ul>
        <h3><a href="{% url 'blog:post_feed' %}">Subscribe to my Rss feed</a></h3>
    </div>
</body>
</html>

mysite/blog/templates/blog/post/detail.html
{% extends 'blog/base.html'%}
{% load blog_tags %}
{% block title%}{{post.title}} {%endblock title%}

{% block content%}
    <h1>{{ post.title }}</h1>
    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|markdown }}
    <p>
        <a href="{% url 'blog:post_share' post.id %}">
            Share this post
        </a>
    </p>
    <h2>相似的帖子： </h2>
    {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
    {% empty %}
        <p>暂时没有！</p>
    {% endfor %}
    {% with comments.count  as total_comments %}
        <h2>
            {{ total_comments }} comment{{ total_comments|pluralize }}
        </h2>
    {% endwith %}

    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Comment {{ forloop.counter }} by {{ comment.name }}
                {{ comment.created }}
            </p>
                {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>暂时没有任何评论！</p>
    {% endfor %}

    {% if new_comment %}
        <h2>你的评论已经添加成功</h2>
    {% else %}
        <h2>发表评论：</h2>
        <form action="{{ post.get_absolute_url }}" method="post">
        {{ comment_form}}
        {% csrf_token %}
        <p>
            <input type="submit" value="发表">
        </p>
    </form>
    {% endif%}
{% endblock content %}

mysite/blog/templates/blog/post/list.html
{% extends "blog/base.html"%}
{% load blog_tags %}
{% block title %}MY Blog {% endblock title%}

{% block content %}
    <h1>My Blog</h1>
    {% if tag %}
        <h2>Posts tagged with "{{ tag.name }}"</h2>
    {% endif %}
    <p class="tags">
        All Tags:
            {% for tag in tags %}
        <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
            {{ tag.name }}
        </a>
            {% empty %}
                当前没有任何标签！
            {% endfor %}
    </p>
    {% for post in posts%}
        <h2>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </h2>
        <p class="tags">Tags: {{ post.tags.all|join:"," }}</p>
        <p class="date">
            Published{{ post.publish }} by {{ post.author }}
        </p>
        {{ post.body|markdown|truncatewords_html:30 }}
    {% empty%}
        现在没有文章！
    {% endfor%}
    {% include 'paginator.html' with page=posts %}
{% endblock content%}

mysite/blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}
{% block title %}Share a post {% endblock %}

{% block content%}
    {% if sent %}
    <h1>E-mail Successfully sent</h1>
    <p>
        "{{post.title }}" was successfully sent to {{ cd.to }}.
    </p>
    {% else %}
        <h1> Share "{{ post.title }}" by e-mail</h1>
        <form action="." method="post">
            {% for field in form%}
                <div>
                    {{ field.errors }}
                    {{ field.label_tag}} {{ field }}
                </div>
            {% endfor %}
            {% csrf_token %}
            <input type="submit" value="send e-mail">
        </form>
    {% endif %}
{% endblock content%}

mysite/blog/templates/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

mysite/blog/templates/paginator.html
<div class="pagination">
    <span class="step-link">
        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
            {% if page.has_next %}
                <a href="?page={{ page.next_page_number }}">Next</a>

            {% endif %}
    </span>
</div>